
[tool.poetry]
name = "xaw-pbe"
version = "1.0.0"
description = "Python backend for XAW"
authors = ["Robert King <varitonium@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.14"
fastapi = "^0.101.1"
fastapi-manage = "^0.8.0"
pydantic = "^2.1.1"
uuid = "^1.30"

# dependencies needed by the ci
black = "26.5.1" 
pycodestyle = "2.15.0"
pydocstyle = "6.3.0
pytest = "9.1.1" 
pytest-asyncio = "1.4.0"
pytest-html = "4.2.0"
ruff = "0.16.9"
bandit = "1.9.4"
sphinx = "9.1.0"
furo = "2025.12.19"
coverage = "7.16.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
